apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mssql-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi    ## grab 200MB of storage from the host...K8S determines where that is physically located