apiVersion: apps/v1
kind: Deployment
metadata:
  name: platforms-depl
spec:
  replicas: 1
  selector:   # selects the template we are createing
    matchLabels:
      app: platformservice
  template: # define what we are deploying
    metadata:
      labels:
        app: platformservice
    spec:
      containers:
        - name: platformservice
          image: sardox/platformservice:latest    ## the actual docker image to deploy
---
## define the cluster service IPs we'll use to allow service to communicate on their private LAN
apiVersion: v1
kind: Service
metadata:
  name: platforms-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: platformservice
  ports:
  - name: platformservice
    protocol: TCP
    port: 80
    targetPort: 80
  - name: platformgrpc
    protocol: TCP
    port: 666
    targetPort: 666
